export const ADD_TODO_ITEM_SUCCESS = "ADD_TODO_ITEM_SUCCESS";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS';
export const RESET_TODO_SUCCESS = 'RESET_TODO_SUCCESS';
export const RESET_TODO_UNMOUNT = 'RESET_TODO_UNMOUNT';
export const ADD_TODO_UNMOUNT = 'ADD_TODO_UNMOUNT';